name: bottom_ani_nav_bar
description: Animated Bottom Navigation bar
version: 0.0.1
homepage: https://github.com/omeasraf/BottomAniNavBar

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.ome.bottom_ani_nav_bar
#         pluginClass: BottomAniNavBarPlugin
#       ios:
#         pluginClass: BottomAniNavBarPlugin
